### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by djmemo** [atom/feedback#37]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Djmemo\AppData\Local\atom\app-0.178.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Djmemo\.atom\packages\feedback\lib\feedback.coffee:7:9)
```

**Comment by kevinsawicki** [comment]
It looks like you've installed the `feedback` package manually to `C:\Users\Djmemo\.atom\packages\feedback`.

This package is bundled with Atom and so if you delete the `C:\Users\Djmemo\.atom\packages\feedback` the version bundled with Atom will be used and this deprecation will not display.
