### ISSUE TITLE
Hover on image link doesn't show a preview

### ISSUE THREAD

**Issue by alistairkb** [atom/feedback#42]
brackets.io has this feature built in, can atom?

**Comment by winstliu** [comment]
Not related to atom/feedback.

**Comment by sfacets** [comment]
Actually, this is relevant feedback...

**Comment by winstliu** [comment]
@sfacets this is the repository for a no-longer-maintained component of Atom, not a repository for providing feedback _about_ Atom.  To suggest feedback, I would suggest using [Discuss](https://discuss.atom.io), the official Atom forum.
